CREATE EVENT traffic_detect ON STREAM detrac DO 
    (SELECT CAR, BUS, PERSON FROM EACH_FRAME WHERE timestamp > 1670269334 
        GROUP BY class ORDER BY SUM(CAR, BUS, PERSON) DESC TOP 10)
USING MODEL yolov5s_416x416 IF NOT EXISTS;

